packages:
  - playground/*

catalogs:
  dev:
    '@antfu/eslint-config': ^4.18.0
    '@prettier/plugin-xml': ^3.4.2
    '@types/node': ^22.16.5
    bumpp: ^10.2.0
    eslint: ^9.31.0
    eslint-plugin-format: ^1.0.1
    lint-staged: ^16.1.2
    simple-git-hooks: ^2.13.0
    taze: ^19.1.0
    tsx: ^4.20.3
    typescript: ^5.8.3
    unbuild: ^3.6.0
    vitest: ^3.2.4
  example/vue2:
    vue: ^2.7.16
  example/vue3:
    vue: ^3.5.18
  prod:
    ansis: ^4.1.0
    cac: ^6.7.14
    consola: ^3.4.2
    tinyexec: ^1.0.1
    tinyglobby: ^0.2.14
  prod-inlined:
    '@posva/prompts': ^2.4.4

ignoreWorkspaceRootCheck: true
verifyDepsBeforeRun: install

# Support more architectures for the future
supportedArchitectures:
  cpu:
    - x64
  os:
    - win32
    - linux
    - darwin
