# Ignore the check of the workspace root directory
ignoreWorkspaceRootCheck: true

# If the dependencies in `node_modules` are not synchronized with those in `package.json`, reinstall them before running the script
verifyDepsBeforeRun: install

# Use a shell emulator to provide cross-platform operation support for npm scripts
# FXIME: Maybe it is equivalent to what the `cross-env` package does
# shellEmulator: true
